### ISSUE TITLE
API mask offset

### ISSUE THREAD

**Issue by Citramones** [w-e-w/sd-webui-nudenet-nsfw-censor#7]
when generating an image in the ui, everything works well, but when generating using the API, the mask on the chest works well, but on the vagina it goes somewhere up

**Comment by w-e-w** [comment]
can you elaborate
by
> when generating an image in the ui

are you doing txt2img / img2img or are you using extras

and by
> when generating using the API

are you using webui's txt2img / img2img api or are you using /nudenet/censor api

**Comment by Citramones** [comment]
> can you elaborate by
> 
> > when generating an image in the ui
> 
> are you doing txt2img / img2img or are you using extras
> 
> and by
> 
> > when generating using the API
> 
> are you using webui's txt2img / img2img api or are you using /nudenet/censor api
> 
> I did a test of both and wasn't able to reproduce the issue both produce the same results if given the same input image and using equivalent args

It's a matter of resolution when I set it to 640*650 Then everything works, but as soon as I switch to 768*512 I have this problem

**Comment by w-e-w** [comment]
are you saying that is a matter of resolution and not whether or not you're using the API or UI?

**Comment by w-e-w** [comment]
I think I found the issue

**Comment by w-e-w** [comment]
see if this PR fix fixes the issue
https://github.com/w-e-w/sd-webui-nudenet-nsfw-censor/pull/8

**Comment by Citramones** [comment]
> see if this PR fix fixes the issue PR #8
I set all values (horizontal and vertical multiplier) ​​to 1 but the problem still remains

**Comment by w-e-w** [comment]
> I set all values (horizontal and vertical multiplier) ​​to 1 but the problem still remains

you seem to have manually set the values to one, this leaves me to believe that you didn't actually pull my updated branch
the reason being that that I coded it too automatically be reset to after update

if you did not manually pull and switch the correct by running commands similar to the below then you likely did not actually update it to the pr branch

if you didn't run the following commands and try again, note you have to replace the path to the extension with your own path

```
git -C "B:\path\to\stable-diffusion-webui\extensions\sd-webui-nudenet-nsfw-censor" pull
git -C "B:\path\to\stable-diffusion-webui\extensions\sd-webui-nudenet-nsfw-censor" switch fix-incorrect-scaling-of-detection

```

---

also, you still haven't answered the first question, how are you using this extension??

at first you seems to be saying that there is a difference between the output of the API versus the UI but did not mention how that you're using the API and how you're using it in the UI because they are at least two methods that you can use it in both ways

later in your second message you mentioned that it is resolution dependent and mention nothing about API or UI

because of this I look at the code again and seems to have found an issue that was causing inaccuracies in scaling in certain cases

I fixed the issue the scalling issues in the PR not in the main branch, but because of your vague answers I still not sure that you're testing it correctly

please send some images (using other means then GitHub like above) and exact test case how are you using the extension so I can replicate your test

also told me to commit hash of this extension that you're currently on

**Comment by w-e-w** [comment]
I was hoping to receive confirmation from you whether or not if the PR would fix the issue
but since you are being silent for 2 days I'm going to merge the PR regardless
